//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.26 at 12:24:08 PM MST 
//

package net.opengis.ogc._100;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Comparison_OperatorsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Comparison_OperatorsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.opengis.net/ogc}Simple_Comparisons"/>
 *         &lt;element ref="{http://www.opengis.net/ogc}Like"/>
 *         &lt;element ref="{http://www.opengis.net/ogc}Between"/>
 *         &lt;element ref="{http://www.opengis.net/ogc}NullCheck"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Comparison_OperatorsType", propOrder = { "simpleComparisonsOrLikeOrBetween" })
public class ComparisonOperatorsType
{

    @XmlElements({ @XmlElement(name = "Between", type = Between.class), @XmlElement(name = "Like", type = Like.class),
        @XmlElement(name = "Simple_Comparisons", type = SimpleComparisons.class),
        @XmlElement(name = "NullCheck", type = NullCheck.class) })
    protected List<Object> simpleComparisonsOrLikeOrBetween;

    /**
     * Gets the value of the simpleComparisonsOrLikeOrBetween property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the simpleComparisonsOrLikeOrBetween
     * property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSimpleComparisonsOrLikeOrBetween().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Between }
     * {@link Like } {@link SimpleComparisons } {@link NullCheck }
     * 
     * 
     */
    public List<Object> getSimpleComparisonsOrLikeOrBetween()
    {
        if (simpleComparisonsOrLikeOrBetween == null)
        {
            simpleComparisonsOrLikeOrBetween = new ArrayList<Object>();
        }
        return this.simpleComparisonsOrLikeOrBetween;
    }

}
