//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.26 at 02:04:22 PM MST 
//

package net.opengis.gml._311;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A MultiSolid is defined by one or more Solids, referenced through solidMember
 * elements.
 * 
 * <p>
 * Java class for MultiSolidType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="MultiSolidType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml}AbstractGeometricAggregateType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/gml}solidMember" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/gml}solidMembers" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiSolidType", propOrder = { "solidMember", "solidMemberList" })
public class MultiSolidType extends AbstractGeometricAggregateType
{

    protected List<SolidPropertyType> solidMember;

    @XmlElement(name = "solidMembers")
    protected SolidArrayPropertyType solidMemberList;

    /**
     * Gets the value of the solidMember property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the solidMember property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSolidMember().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SolidPropertyType }
     * 
     * 
     */
    public List<SolidPropertyType> getSolidMember()
    {
        if (solidMember == null)
        {
            solidMember = new ArrayList<SolidPropertyType>();
        }
        return this.solidMember;
    }

    /**
     * Gets the value of the solidMemberList property.
     * 
     * @return possible object is {@link SolidArrayPropertyType }
     * 
     */
    public SolidArrayPropertyType getSolidMemberList()
    {
        return solidMemberList;
    }

    /**
     * Sets the value of the solidMemberList property.
     * 
     * @param value allowed object is {@link SolidArrayPropertyType }
     * 
     */
    public void setSolidMemberList(SolidArrayPropertyType value)
    {
        this.solidMemberList = value;
    }

}
