//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.30 at 02:21:16 PM MDT 
//


package com.bitsys.fade.mist.state.v4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BinMethodsEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BinMethodsEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Unique"/>
 *     &lt;enumeration value="Date"/>
 *     &lt;enumeration value="Numeric"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BinMethodsEnumType")
@XmlEnum
public enum BinMethodsEnumType {

    @XmlEnumValue("Unique")
    UNIQUE("Unique"),
    @XmlEnumValue("Date")
    DATE("Date"),
    @XmlEnumValue("Numeric")
    NUMERIC("Numeric");
    private final String value;

    BinMethodsEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BinMethodsEnumType fromValue(String v) {
        for (BinMethodsEnumType c: BinMethodsEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
