//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.30 at 02:21:16 PM MDT 
//


package com.bitsys.fade.mist.state.v4;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *         An action that styles features.
 *       
 * 
 * <p>Java class for FeatureStyleActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureStyleActionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bit-sys.com/mist/state/v4}AbstractActionType">
 *       &lt;all>
 *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="opacity" type="{http://www.bit-sys.com/mist/state/v4}DecimalPercentageType" minOccurs="0"/>
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="showRotation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="rotationColumn" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="shape" type="{http://www.bit-sys.com/mist/state/v4}ShapeType" minOccurs="0"/>
 *         &lt;element name="centerShape" type="{http://www.bit-sys.com/mist/state/v4}ShapeType" minOccurs="0"/>
 *         &lt;element name="iconSrc" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureStyleActionType", propOrder = {
    "color",
    "opacity",
    "size",
    "showRotation",
    "rotationColumn",
    "shape",
    "centerShape",
    "iconSrc"
})
public class FeatureStyleActionType
    extends AbstractActionType
{

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String color;
    protected BigDecimal opacity;
    protected BigDecimal size;
    protected Boolean showRotation;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String rotationColumn;
    @XmlSchemaType(name = "token")
    protected ShapeType shape;
    @XmlSchemaType(name = "token")
    protected ShapeType centerShape;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String iconSrc;

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    public boolean isSetColor() {
        return (this.color!= null);
    }

    /**
     * Gets the value of the opacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOpacity() {
        return opacity;
    }

    /**
     * Sets the value of the opacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOpacity(BigDecimal value) {
        this.opacity = value;
    }

    public boolean isSetOpacity() {
        return (this.opacity!= null);
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSize(BigDecimal value) {
        this.size = value;
    }

    public boolean isSetSize() {
        return (this.size!= null);
    }

    /**
     * Gets the value of the showRotation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowRotation() {
        return showRotation;
    }

    /**
     * Sets the value of the showRotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowRotation(Boolean value) {
        this.showRotation = value;
    }

    public boolean isSetShowRotation() {
        return (this.showRotation!= null);
    }

    /**
     * Gets the value of the rotationColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRotationColumn() {
        return rotationColumn;
    }

    /**
     * Sets the value of the rotationColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRotationColumn(String value) {
        this.rotationColumn = value;
    }

    public boolean isSetRotationColumn() {
        return (this.rotationColumn!= null);
    }

    /**
     * Gets the value of the shape property.
     * 
     * @return
     *     possible object is
     *     {@link ShapeType }
     *     
     */
    public ShapeType getShape() {
        return shape;
    }

    /**
     * Sets the value of the shape property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShapeType }
     *     
     */
    public void setShape(ShapeType value) {
        this.shape = value;
    }

    public boolean isSetShape() {
        return (this.shape!= null);
    }

    /**
     * Gets the value of the centerShape property.
     * 
     * @return
     *     possible object is
     *     {@link ShapeType }
     *     
     */
    public ShapeType getCenterShape() {
        return centerShape;
    }

    /**
     * Sets the value of the centerShape property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShapeType }
     *     
     */
    public void setCenterShape(ShapeType value) {
        this.centerShape = value;
    }

    public boolean isSetCenterShape() {
        return (this.centerShape!= null);
    }

    /**
     * Gets the value of the iconSrc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconSrc() {
        return iconSrc;
    }

    /**
     * Sets the value of the iconSrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconSrc(String value) {
        this.iconSrc = value;
    }

    public boolean isSetIconSrc() {
        return (this.iconSrc!= null);
    }

}
