//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.30 at 12:22:16 PM MDT 
//


package com.bitsys.fade.mist.state.v4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         A set of data hold intervals, used in animations. A hold interval
 *         defines an interval in which data is held and not animated (e.g.: the
 *         data that temporally falls in this interval will be displayed for the
 *         entire animation instead of for its defined temporal span).
 *       
 * 
 * <p>Java class for HeldIntervalsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeldIntervalsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="held" type="{http://www.bit-sys.com/mist/state/v4}HeldIntervalType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeldIntervalsType", propOrder = {
    "held"
})
public class HeldIntervalsType {

    protected List<HeldIntervalType> held;

    /**
     * Gets the value of the held property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the held property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeld().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HeldIntervalType }
     * 
     * 
     */
    public List<HeldIntervalType> getHeld() {
        if (held == null) {
            held = new ArrayList<HeldIntervalType>();
        }
        return this.held;
    }

    public boolean isSetHeld() {
        return ((this.held!= null)&&(!this.held.isEmpty()));
    }

    public void unsetHeld() {
        this.held = null;
    }

}
