//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 10:22:41 AM MST 
//


package com.bitsys.fade.mist.state.v4;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *         A definition of an style for displaying a feature using an icon. All 
 *         features in the layer will use the same configuration, and icons will 
 *         be displayed for each feature in the layer, as configured in the style.
 *       
 * 
 * <p>Java class for IconStyleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IconStyleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="iconDefaultPointSize" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="iconDefaultTo" type="{http://www.bit-sys.com/mist/state/v4}IconDefaultType" minOccurs="0"/>
 *         &lt;element name="iconScale" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="defaultIconURL" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="iconXOffset" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="iconYOffset" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="mixIconElementColor" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IconStyleType", propOrder = {

})
public class IconStyleType {

    protected BigDecimal iconDefaultPointSize;
    @XmlSchemaType(name = "token")
    protected IconDefaultType iconDefaultTo;
    protected BigDecimal iconScale;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String defaultIconURL;
    protected BigInteger iconXOffset;
    protected BigInteger iconYOffset;
    protected Boolean mixIconElementColor;

    /**
     * Gets the value of the iconDefaultPointSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIconDefaultPointSize() {
        return iconDefaultPointSize;
    }

    /**
     * Sets the value of the iconDefaultPointSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIconDefaultPointSize(BigDecimal value) {
        this.iconDefaultPointSize = value;
    }

    public boolean isSetIconDefaultPointSize() {
        return (this.iconDefaultPointSize!= null);
    }

    /**
     * Gets the value of the iconDefaultTo property.
     * 
     * @return
     *     possible object is
     *     {@link IconDefaultType }
     *     
     */
    public IconDefaultType getIconDefaultTo() {
        return iconDefaultTo;
    }

    /**
     * Sets the value of the iconDefaultTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IconDefaultType }
     *     
     */
    public void setIconDefaultTo(IconDefaultType value) {
        this.iconDefaultTo = value;
    }

    public boolean isSetIconDefaultTo() {
        return (this.iconDefaultTo!= null);
    }

    /**
     * Gets the value of the iconScale property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIconScale() {
        return iconScale;
    }

    /**
     * Sets the value of the iconScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIconScale(BigDecimal value) {
        this.iconScale = value;
    }

    public boolean isSetIconScale() {
        return (this.iconScale!= null);
    }

    /**
     * Gets the value of the defaultIconURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultIconURL() {
        return defaultIconURL;
    }

    /**
     * Sets the value of the defaultIconURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultIconURL(String value) {
        this.defaultIconURL = value;
    }

    public boolean isSetDefaultIconURL() {
        return (this.defaultIconURL!= null);
    }

    /**
     * Gets the value of the iconXOffset property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIconXOffset() {
        return iconXOffset;
    }

    /**
     * Sets the value of the iconXOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIconXOffset(BigInteger value) {
        this.iconXOffset = value;
    }

    public boolean isSetIconXOffset() {
        return (this.iconXOffset!= null);
    }

    /**
     * Gets the value of the iconYOffset property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIconYOffset() {
        return iconYOffset;
    }

    /**
     * Sets the value of the iconYOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIconYOffset(BigInteger value) {
        this.iconYOffset = value;
    }

    public boolean isSetIconYOffset() {
        return (this.iconYOffset!= null);
    }

    /**
     * Gets the value of the mixIconElementColor property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMixIconElementColor() {
        return mixIconElementColor;
    }

    /**
     * Sets the value of the mixIconElementColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMixIconElementColor(Boolean value) {
        this.mixIconElementColor = value;
    }

    public boolean isSetMixIconElementColor() {
        return (this.mixIconElementColor!= null);
    }

}
