//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 10:22:41 AM MST 
//

package com.bitsys.fade.mist.state.v4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for MappingTypes.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="MappingTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Altitude"/>
 *     &lt;enumeration value="LatLon"/>
 *     &lt;enumeration value="Latitude"/>
 *     &lt;enumeration value="Longitude"/>
 *     &lt;enumeration value="MGRSMapping"/>
 *     &lt;enumeration value="Orientation"/>
 *     &lt;enumeration value="Position"/>
 *     &lt;enumeration value="Radius"/>
 *     &lt;enumeration value="SemiMajor"/>
 *     &lt;enumeration value="SemiMinor"/>
 *     &lt;enumeration value="WKTGeometry"/>
 *     &lt;enumeration value="DateTime"/>
 *     &lt;enumeration value="Date"/>
 *     &lt;enumeration value="Time"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MappingTypes")
@XmlEnum
public enum MappingTypes
{

    @XmlEnumValue("Altitude")
    ALTITUDE("Altitude"), @XmlEnumValue("LatLon")
    LAT_LON("LatLon"), @XmlEnumValue("Latitude")
    LATITUDE("Latitude"), @XmlEnumValue("Longitude")
    LONGITUDE("Longitude"), @XmlEnumValue("MGRSMapping")
    MGRS_MAPPING("MGRSMapping"), @XmlEnumValue("Orientation")
    ORIENTATION("Orientation"), @XmlEnumValue("Position")
    POSITION("Position"), @XmlEnumValue("Radius")
    RADIUS("Radius"), @XmlEnumValue("SemiMajor")
    SEMI_MAJOR("SemiMajor"), @XmlEnumValue("SemiMinor")
    SEMI_MINOR("SemiMinor"), @XmlEnumValue("WKTGeometry")
    WKT_GEOMETRY("WKTGeometry"), @XmlEnumValue("DateTime")
    DATE_TIME("DateTime"), @XmlEnumValue("Date")
    DATE("Date"), @XmlEnumValue("Time")
    TIME("Time");
    private final String value;

    MappingTypes(String v)
    {
        value = v;
    }

    public String value()
    {
        return value;
    }

    public static MappingTypes fromValue(String v)
    {
        for (MappingTypes c : MappingTypes.values())
        {
            if (c.value.equals(v))
            {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
