//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.30 at 02:21:16 PM MDT 
//


package com.bitsys.fade.mist.state.v4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MappingSubType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MappingSubType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="instant"/>
 *     &lt;enumeration value="start"/>
 *     &lt;enumeration value="end"/>
 *     &lt;enumeration value="publication"/>
 *     &lt;enumeration value="Lat/Lon"/>
 *     &lt;enumeration value="Lon/Lat"/>
 *     &lt;enumeration value="MGRS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MappingSubType")
@XmlEnum
public enum MappingSubType {

    @XmlEnumValue("instant")
    INSTANT("instant"),
    @XmlEnumValue("start")
    START("start"),
    @XmlEnumValue("end")
    END("end"),
    @XmlEnumValue("publication")
    PUBLICATION("publication"),
    @XmlEnumValue("Lat/Lon")
    LAT_LON("Lat/Lon"),
    @XmlEnumValue("Lon/Lat")
    LON_LAT("Lon/Lat"),
    MGRS("MGRS");
    private final String value;

    MappingSubType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MappingSubType fromValue(String v) {
        for (MappingSubType c: MappingSubType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
