//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 10:22:41 AM MST 
//

package com.bitsys.fade.mist.state.v4;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.bitsys.fade.mist.state.v4 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

    private final static QName _State_QNAME = new QName("http://www.bit-sys.com/mist/state/v4", "state");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: com.bitsys.fade.mist.state.v4
     * 
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link StateType }
     * 
     */
    public StateType createStateType()
    {
        return new StateType();
    }

    /**
     * Create an instance of {@link MappingType }
     * 
     */
    public MappingType createMappingType()
    {
        return new MappingType();
    }

    /**
     * Create an instance of {@link NameValueType }
     * 
     */
    public NameValueType createNameValueType()
    {
        return new NameValueType();
    }

    /**
     * Create an instance of {@link HeldIntervalType }
     * 
     */
    public HeldIntervalType createHeldIntervalType()
    {
        return new HeldIntervalType();
    }

    /**
     * Create an instance of {@link ExtentsType }
     * 
     */
    public ExtentsType createExtentsType()
    {
        return new ExtentsType();
    }

    /**
     * Create an instance of {@link ProjectionsType }
     * 
     */
    public ProjectionsType createProjectionsType()
    {
        return new ProjectionsType();
    }

    /**
     * Create an instance of {@link MapType }
     * 
     */
    public MapType createMapType()
    {
        return new MapType();
    }

    /**
     * Create an instance of {@link BinMethodSequenceType }
     * 
     */
    public BinMethodSequenceType createBinMethodSequenceType()
    {
        return new BinMethodSequenceType();
    }

    /**
     * Create an instance of {@link QueryEntryType }
     * 
     */
    public QueryEntryType createQueryEntryType()
    {
        return new QueryEntryType();
    }

    /**
     * Create an instance of {@link LayerParamsType }
     * 
     */
    public LayerParamsType createLayerParamsType()
    {
        return new LayerParamsType();
    }

    /**
     * Create an instance of {@link LabelColumnType }
     * 
     */
    public LabelColumnType createLabelColumnType()
    {
        return new LabelColumnType();
    }

    /**
     * Create an instance of {@link BinMethodType }
     * 
     */
    public BinMethodType createBinMethodType()
    {
        return new BinMethodType();
    }

    /**
     * Create an instance of {@link ColumnsType }
     * 
     */
    public ColumnsType createColumnsType()
    {
        return new ColumnsType();
    }

    /**
     * Create an instance of {@link IconStyleType }
     * 
     */
    public IconStyleType createIconStyleType()
    {
        return new IconStyleType();
    }

    /**
     * Create an instance of {@link QueryAreasType }
     * 
     */
    public QueryAreasType createQueryAreasType()
    {
        return new QueryAreasType();
    }

    /**
     * Create an instance of {@link NameValueSequenceType }
     * 
     */
    public NameValueSequenceType createNameValueSequenceType()
    {
        return new NameValueSequenceType();
    }

    /**
     * Create an instance of {@link LayerType }
     * 
     */
    public LayerType createLayerType()
    {
        return new LayerType();
    }

    /**
     * Create an instance of {@link LayersType }
     * 
     */
    public LayersType createLayersType()
    {
        return new LayersType();
    }

    /**
     * Create an instance of {@link TimeSequenceType }
     * 
     */
    public TimeSequenceType createTimeSequenceType()
    {
        return new TimeSequenceType();
    }

    /**
     * Create an instance of {@link ColorModelType }
     * 
     */
    public ColorModelType createColorModelType()
    {
        return new ColorModelType();
    }

    /**
     * Create an instance of {@link HeldIntervalsType }
     * 
     */
    public HeldIntervalsType createHeldIntervalsType()
    {
        return new HeldIntervalsType();
    }

    /**
     * Create an instance of {@link UrlsType }
     * 
     */
    public UrlsType createUrlsType()
    {
        return new UrlsType();
    }

    /**
     * Create an instance of {@link TagsType }
     * 
     */
    public TagsType createTagsType()
    {
        return new TagsType();
    }

    /**
     * Create an instance of {@link TimeType }
     * 
     */
    public TimeType createTimeType()
    {
        return new TimeType();
    }

    /**
     * Create an instance of {@link QueryAreaType }
     * 
     */
    public QueryAreaType createQueryAreaType()
    {
        return new QueryAreaType();
    }

    /**
     * Create an instance of {@link FiltersType }
     * 
     */
    public FiltersType createFiltersType()
    {
        return new FiltersType();
    }

    /**
     * Create an instance of {@link QueryEntriesType }
     * 
     */
    public QueryEntriesType createQueryEntriesType()
    {
        return new QueryEntriesType();
    }

    /**
     * Create an instance of {@link BasicFeatureStyleType }
     * 
     */
    public BasicFeatureStyleType createBasicFeatureStyleType()
    {
        return new BasicFeatureStyleType();
    }

    /**
     * Create an instance of {@link TimeAnimationType }
     * 
     */
    public TimeAnimationType createTimeAnimationType()
    {
        return new TimeAnimationType();
    }

    /**
     * Create an instance of {@link TimeFadeType }
     * 
     */
    public TimeFadeType createTimeFadeType()
    {
        return new TimeFadeType();
    }

    /**
     * Create an instance of {@link ExclusionAreasType }
     * 
     */
    public ExclusionAreasType createExclusionAreasType()
    {
        return new ExclusionAreasType();
    }

    /**
     * Create an instance of {@link StyleType }
     * 
     */
    public StyleType createStyleType()
    {
        return new StyleType();
    }

    /**
     * Create an instance of {@link GraphViewType }
     * 
     */
    public GraphViewType createGraphViewType()
    {
        return new GraphViewType();
    }

    /**
     * Create an instance of {@link StylesType }
     * 
     */
    public StylesType createStylesType()
    {
        return new StylesType();
    }

    /**
     * Create an instance of {@link LabelColumnsType }
     * 
     */
    public LabelColumnsType createLabelColumnsType()
    {
        return new LabelColumnsType();
    }

    /**
     * Create an instance of {@link ExclusionAreaType }
     * 
     */
    public ExclusionAreaType createExclusionAreaType()
    {
        return new ExclusionAreaType();
    }

    /**
     * Create an instance of {@link MappingsType }
     * 
     */
    public MappingsType createMappingsType()
    {
        return new MappingsType();
    }

    /**
     * Create an instance of {@link FormatsType }
     * 
     */
    public FormatsType createFormatsType()
    {
        return new FormatsType();
    }

    /**
     * Create an instance of {@link StreamOptionsType }
     * 
     */
    public StreamOptionsType createStreamOptionsType()
    {
        return new StreamOptionsType();
    }

    /**
     * Create an instance of {@link ObjectPreviewType }
     * 
     */
    public ObjectPreviewType createObjectPreviewType()
    {
        return new ObjectPreviewType();
    }

    /**
     * Create an instance of {@link BinSettingsType }
     * 
     */
    public BinSettingsType createBinSettingsType()
    {
        return new BinSettingsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StateType
     * }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.bit-sys.com/mist/state/v4", name = "state")
    public JAXBElement<StateType> createState(StateType value)
    {
        return new JAXBElement<StateType>(_State_QNAME, StateType.class, null, value);
    }

}
