//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 10:22:41 AM MST 
//

package com.bitsys.fade.mist.state.v4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 * Defines object properties for object layers.
 * 
 * 
 * <p>
 * Java class for ObjectPreviewType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectPreviewType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="coi" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 *         &lt;element name="temporal" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectPreviewType", propOrder = {

})
public class ObjectPreviewType
{

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String id;

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String coi;

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String enabled;

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String type;

    protected Boolean temporal;

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getId()
    {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setId(String value)
    {
        this.id = value;
    }

    public boolean isSetId()
    {
        return (this.id != null);
    }

    /**
     * Gets the value of the coi property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCoi()
    {
        return coi;
    }

    /**
     * Sets the value of the coi property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCoi(String value)
    {
        this.coi = value;
    }

    public boolean isSetCoi()
    {
        return (this.coi != null);
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEnabled()
    {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setEnabled(String value)
    {
        this.enabled = value;
    }

    public boolean isSetEnabled()
    {
        return (this.enabled != null);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName()
    {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setName(String value)
    {
        this.name = value;
    }

    public boolean isSetName()
    {
        return (this.name != null);
    }

    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getType()
    {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setType(String value)
    {
        this.type = value;
    }

    public boolean isSetType()
    {
        return (this.type != null);
    }

    /**
     * Gets the value of the temporal property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isTemporal()
    {
        return temporal;
    }

    /**
     * Sets the value of the temporal property.
     * 
     * @param value allowed object is {@link Boolean }
     * 
     */
    public void setTemporal(Boolean value)
    {
        this.temporal = value;
    }

    public boolean isSetTemporal()
    {
        return (this.temporal != null);
    }

}
