//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 10:22:41 AM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bit-sys.com/mist/state/v4", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bitsys.fade.mist.state.v4;
