//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.26 at 02:04:22 PM MST 
//

package net.opengis.ogc._110;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

import net.opengis.gml._311.AbstractCurveType;
import net.opengis.gml._311.AbstractGeometricAggregateType;
import net.opengis.gml._311.AbstractGeometricPrimitiveType;
import net.opengis.gml._311.AbstractGeometryType;
import net.opengis.gml._311.AbstractRingType;
import net.opengis.gml._311.AbstractSolidType;
import net.opengis.gml._311.AbstractSurfaceType;
import net.opengis.gml._311.CompositeCurveType;
import net.opengis.gml._311.CompositeSolidType;
import net.opengis.gml._311.CompositeSurfaceType;
import net.opengis.gml._311.CurveType;
import net.opengis.gml._311.EnvelopeType;
import net.opengis.gml._311.EnvelopeWithTimePeriodType;
import net.opengis.gml._311.GeometricComplexType;
import net.opengis.gml._311.GridType;
import net.opengis.gml._311.LineStringType;
import net.opengis.gml._311.LinearRingType;
import net.opengis.gml._311.MultiCurveType;
import net.opengis.gml._311.MultiGeometryType;
import net.opengis.gml._311.MultiLineStringType;
import net.opengis.gml._311.MultiPointType;
import net.opengis.gml._311.MultiPolygonType;
import net.opengis.gml._311.MultiSolidType;
import net.opengis.gml._311.MultiSurfaceType;
import net.opengis.gml._311.OrientableCurveType;
import net.opengis.gml._311.OrientableSurfaceType;
import net.opengis.gml._311.PointType;
import net.opengis.gml._311.PolygonType;
import net.opengis.gml._311.PolyhedralSurfaceType;
import net.opengis.gml._311.RectifiedGridType;
import net.opengis.gml._311.RingType;
import net.opengis.gml._311.SolidType;
import net.opengis.gml._311.SurfaceType;
import net.opengis.gml._311.TinType;
import net.opengis.gml._311.TriangulatedSurfaceType;

/**
 * <p>
 * Java class for BinarySpatialOpType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="BinarySpatialOpType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/ogc}SpatialOpsType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/ogc}PropertyName"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.opengis.net/gml}_Geometry"/>
 *           &lt;element ref="{http://www.opengis.net/gml}Envelope"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BinarySpatialOpType", propOrder = { "propertyName", "geometry", "envelope" })
public class BinarySpatialOpType extends SpatialOpsType
{

    @XmlElement(name = "PropertyName", required = true)
    protected PropertyNameType propertyName;

    @XmlElementRef(name = "_Geometry", namespace = "http://www.opengis.net/gml", type = JAXBElement.class)
    protected JAXBElement<? extends AbstractGeometryType> geometry;

    @XmlElementRef(name = "Envelope", namespace = "http://www.opengis.net/gml", type = JAXBElement.class)
    protected JAXBElement<? extends EnvelopeType> envelope;

    /**
     * Gets the value of the propertyName property.
     * 
     * @return possible object is {@link PropertyNameType }
     * 
     */
    public PropertyNameType getPropertyName()
    {
        return propertyName;
    }

    /**
     * Sets the value of the propertyName property.
     * 
     * @param value allowed object is {@link PropertyNameType }
     * 
     */
    public void setPropertyName(PropertyNameType value)
    {
        this.propertyName = value;
    }

    /**
     * Gets the value of the geometry property.
     * 
     * @return possible object is {@link JAXBElement
     *         }{@code <}{@link MultiCurveType }{@code >} {@link JAXBElement
     *         }{@code <}{@link RingType }{@code >} {@link JAXBElement
     *         }{@code <}{@link TinType }{@code >} {@link JAXBElement
     *         }{@code <}{@link AbstractGeometricPrimitiveType }{@code >}
     *         {@link JAXBElement }{@code <}{@link AbstractSurfaceType
     *         }{@code >} {@link JAXBElement }{@code <}{@link SurfaceType
     *         }{@code >} {@link JAXBElement }{@code <}{@link MultiGeometryType
     *         }{@code >} {@link JAXBElement }{@code <}{@link MultiPointType
     *         }{@code >} {@link JAXBElement }{@code <}{@link LineStringType
     *         }{@code >} {@link JAXBElement }{@code <}{@link LinearRingType
     *         }{@code >} {@link JAXBElement
     *         }{@code <}{@link AbstractGeometryType }{@code >}
     *         {@link JAXBElement }{@code <}{@link CompositeCurveType }{@code >}
     *         {@link JAXBElement }{@code <}{@link OrientableCurveType
     *         }{@code >} {@link JAXBElement
     *         }{@code <}{@link AbstractGeometryType }{@code >}
     *         {@link JAXBElement }{@code <}{@link AbstractSolidType }{@code >}
     *         {@link JAXBElement }{@code <}{@link AbstractRingType }{@code >}
     *         {@link JAXBElement }{@code <}{@link SolidType }{@code >}
     *         {@link JAXBElement }{@code <}{@link TriangulatedSurfaceType
     *         }{@code >} {@link JAXBElement
     *         }{@code <}{@link MultiLineStringType }{@code >}
     *         {@link JAXBElement
     *         }{@code <}{@link AbstractGeometricAggregateType }{@code >}
     *         {@link JAXBElement }{@code <}{@link OrientableSurfaceType
     *         }{@code >} {@link JAXBElement }{@code <}{@link GridType
     *         }{@code >} {@link JAXBElement }{@code <}{@link MultiPolygonType
     *         }{@code >} {@link JAXBElement }{@code <}{@link PolygonType
     *         }{@code >} {@link JAXBElement }{@code <}{@link CompositeSolidType
     *         }{@code >} {@link JAXBElement }{@code <}{@link MultiSurfaceType
     *         }{@code >} {@link JAXBElement
     *         }{@code <}{@link GeometricComplexType }{@code >}
     *         {@link JAXBElement }{@code <}{@link CurveType }{@code >}
     *         {@link JAXBElement }{@code <}{@link AbstractCurveType }{@code >}
     *         {@link JAXBElement }{@code <}{@link CompositeSurfaceType
     *         }{@code >} {@link JAXBElement
     *         }{@code <}{@link PolyhedralSurfaceType }{@code >}
     *         {@link JAXBElement }{@code <}{@link MultiSolidType }{@code >}
     *         {@link JAXBElement }{@code <}{@link RectifiedGridType }{@code >}
     *         {@link JAXBElement }{@code <}{@link PointType }{@code >}
     * 
     */
    public JAXBElement<? extends AbstractGeometryType> getGeometry()
    {
        return geometry;
    }

    /**
     * Sets the value of the geometry property.
     * 
     * @param value allowed object is {@link JAXBElement
     *            }{@code <}{@link MultiCurveType }{@code >} {@link JAXBElement
     *            }{@code <}{@link RingType }{@code >} {@link JAXBElement
     *            }{@code <}{@link TinType }{@code >} {@link JAXBElement
     *            }{@code <}{@link AbstractGeometricPrimitiveType }{@code >}
     *            {@link JAXBElement }{@code <}{@link AbstractSurfaceType
     *            }{@code >} {@link JAXBElement }{@code <}{@link SurfaceType
     *            }{@code >} {@link JAXBElement
     *            }{@code <}{@link MultiGeometryType }{@code >}
     *            {@link JAXBElement }{@code <}{@link MultiPointType }{@code >}
     *            {@link JAXBElement }{@code <}{@link LineStringType }{@code >}
     *            {@link JAXBElement }{@code <}{@link LinearRingType }{@code >}
     *            {@link JAXBElement }{@code <}{@link AbstractGeometryType
     *            }{@code >} {@link JAXBElement
     *            }{@code <}{@link CompositeCurveType }{@code >}
     *            {@link JAXBElement }{@code <}{@link OrientableCurveType
     *            }{@code >} {@link JAXBElement
     *            }{@code <}{@link AbstractGeometryType }{@code >}
     *            {@link JAXBElement }{@code <}{@link AbstractSolidType
     *            }{@code >} {@link JAXBElement
     *            }{@code <}{@link AbstractRingType }{@code >}
     *            {@link JAXBElement }{@code <}{@link SolidType }{@code >}
     *            {@link JAXBElement }{@code <}{@link TriangulatedSurfaceType
     *            }{@code >} {@link JAXBElement
     *            }{@code <}{@link MultiLineStringType }{@code >}
     *            {@link JAXBElement
     *            }{@code <}{@link AbstractGeometricAggregateType }{@code >}
     *            {@link JAXBElement }{@code <}{@link OrientableSurfaceType
     *            }{@code >} {@link JAXBElement }{@code <}{@link GridType
     *            }{@code >} {@link JAXBElement
     *            }{@code <}{@link MultiPolygonType }{@code >}
     *            {@link JAXBElement }{@code <}{@link PolygonType }{@code >}
     *            {@link JAXBElement }{@code <}{@link CompositeSolidType
     *            }{@code >} {@link JAXBElement
     *            }{@code <}{@link MultiSurfaceType }{@code >}
     *            {@link JAXBElement }{@code <}{@link GeometricComplexType
     *            }{@code >} {@link JAXBElement }{@code <}{@link CurveType
     *            }{@code >} {@link JAXBElement
     *            }{@code <}{@link AbstractCurveType }{@code >}
     *            {@link JAXBElement }{@code <}{@link CompositeSurfaceType
     *            }{@code >} {@link JAXBElement
     *            }{@code <}{@link PolyhedralSurfaceType }{@code >}
     *            {@link JAXBElement }{@code <}{@link MultiSolidType }{@code >}
     *            {@link JAXBElement }{@code <}{@link RectifiedGridType
     *            }{@code >} {@link JAXBElement }{@code <}{@link PointType
     *            }{@code >}
     * 
     */
    public void setGeometry(JAXBElement<? extends AbstractGeometryType> value)
    {
        this.geometry = (value);
    }

    /**
     * Gets the value of the envelope property.
     * 
     * @return possible object is {@link JAXBElement
     *         }{@code <}{@link EnvelopeType }{@code >} {@link JAXBElement
     *         }{@code <}{@link EnvelopeWithTimePeriodType }{@code >}
     * 
     */
    public JAXBElement<? extends EnvelopeType> getEnvelope()
    {
        return envelope;
    }

    /**
     * Sets the value of the envelope property.
     * 
     * @param value allowed object is {@link JAXBElement
     *            }{@code <}{@link EnvelopeType }{@code >} {@link JAXBElement
     *            }{@code <}{@link EnvelopeWithTimePeriodType }{@code >}
     * 
     */
    public void setEnvelope(JAXBElement<? extends EnvelopeType> value)
    {
        this.envelope = (value);
    }

}
