//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.22 at 02:23:57 PM MST 
//

package net.opengis.cat.csw._202;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Requests the actual values of some specified request parameter or other data
 * element.
 * 
 * <p>
 * Java class for GetDomainType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="GetDomainType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/cat/csw/2.0.2}RequestBaseType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="PropertyName" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *           &lt;element name="ParameterName" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetDomainType", propOrder = { "propertyName", "parameterName" })
public class GetDomainType extends RequestBaseType
{

    @XmlElement(name = "PropertyName")
    @XmlSchemaType(name = "anyURI")
    protected String propertyName;

    @XmlElement(name = "ParameterName")
    @XmlSchemaType(name = "anyURI")
    protected String parameterName;

    /**
     * Gets the value of the propertyName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPropertyName()
    {
        return propertyName;
    }

    /**
     * Sets the value of the propertyName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPropertyName(String value)
    {
        this.propertyName = value;
    }

    /**
     * Gets the value of the parameterName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getParameterName()
    {
        return parameterName;
    }

    /**
     * Sets the value of the parameterName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setParameterName(String value)
    {
        this.parameterName = value;
    }

}
