//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.22 at 02:23:57 PM MST 
//

package net.opengis.cat.csw._202;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.w3c.dom.Element;

/**
 * A schema component includes a schema fragment (type definition) or an entire
 * schema from some target namespace; the schema language is identified by URI.
 * If the component is a schema fragment its parent MUST be referenced
 * (parentSchema).
 * 
 * <p>
 * Java class for SchemaComponentType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SchemaComponentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any processContents='lax'/>
 *       &lt;/sequence>
 *       &lt;attribute name="targetNamespace" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="parentSchema" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="schemaLanguage" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SchemaComponentType", propOrder = { "content" })
public class SchemaComponentType
{

    @XmlMixed
    @XmlAnyElement(lax = true)
    protected List<Object> content;

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String targetNamespace;

    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String parentSchema;

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String schemaLanguage;

    /**
     * A schema component includes a schema fragment (type definition) or an
     * entire schema from some target namespace; the schema language is
     * identified by URI. If the component is a schema fragment its parent MUST
     * be referenced (parentSchema).Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * {@link Element } {@link Object }
     * 
     * 
     */
    public List<Object> getContent()
    {
        if (content == null)
        {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the targetNamespace property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTargetNamespace()
    {
        return targetNamespace;
    }

    /**
     * Sets the value of the targetNamespace property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTargetNamespace(String value)
    {
        this.targetNamespace = value;
    }

    /**
     * Gets the value of the parentSchema property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getParentSchema()
    {
        return parentSchema;
    }

    /**
     * Sets the value of the parentSchema property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setParentSchema(String value)
    {
        this.parentSchema = value;
    }

    /**
     * Gets the value of the schemaLanguage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSchemaLanguage()
    {
        return schemaLanguage;
    }

    /**
     * Sets the value of the schemaLanguage property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSchemaLanguage(String value)
    {
        this.schemaLanguage = value;
    }

}
