//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.26 at 02:04:22 PM MST 
//

package net.opengis.wfs._110;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

/**
 * 
 * The DescribeFeatureType operation allows a client application to request that
 * a Web Feature Service describe one or more feature types. A Web Feature
 * Service must be able to generate feature descriptions as valid GML3
 * application schemas.
 * 
 * The schemas generated by the DescribeFeatureType operation can be used by a
 * client application to validate the output.
 * 
 * Feature instances within the WFS interface must be specified using GML3. The
 * schema of feature instances specified within the WFS interface must validate
 * against the feature schemas generated by the DescribeFeatureType request.
 * 
 * 
 * <p>
 * Java class for DescribeFeatureTypeType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DescribeFeatureTypeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/wfs}BaseRequestType">
 *       &lt;sequence>
 *         &lt;element name="TypeName" type="{http://www.w3.org/2001/XMLSchema}QName" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="outputFormat" type="{http://www.w3.org/2001/XMLSchema}string" default="text/xml; subtype=gml/3.1.1" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescribeFeatureTypeType", propOrder = { "typeName" })
public class DescribeFeatureTypeType extends BaseRequestType
{

    @XmlElement(name = "TypeName")
    protected List<QName> typeName;

    @XmlAttribute(name = "outputFormat")
    protected String outputFormat;

    /**
     * Gets the value of the typeName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the typeName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTypeName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link QName }
     * 
     * 
     */
    public List<QName> getTypeName()
    {
        if (typeName == null)
        {
            typeName = new ArrayList<QName>();
        }
        return this.typeName;
    }

    /**
     * Gets the value of the outputFormat property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOutputFormat()
    {
        if (outputFormat == null)
        {
            return "text/xml; subtype=gml/3.1.1";
        }
        else
        {
            return outputFormat;
        }
    }

    /**
     * Sets the value of the outputFormat property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOutputFormat(String value)
    {
        this.outputFormat = value;
    }

}
