//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.26 at 02:04:22 PM MST 
//

package net.opengis.wfs._110;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Request to a WFS to perform the GetCapabilities operation. This operation
 * allows a client to retrieve a Capabilities XML document providing metadata
 * for the specific WFS server.
 * 
 * The GetCapapbilities element is used to request that a Web Feature Service
 * generate an XML document describing the organization providing the service,
 * the WFS operations that the service supports, a list of feature types that
 * the service can operate on and list of filtering capabilities that the
 * service support. Such an XML document is called a capabilities document.
 * 
 * 
 * <p>
 * Java class for GetCapabilitiesType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="GetCapabilitiesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/ows}GetCapabilitiesType">
 *       &lt;attribute name="service" type="{http://www.opengis.net/ows}ServiceType" default="WFS" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetCapabilitiesType")
public class GetCapabilitiesType extends net.opengis.ows._100.GetCapabilitiesType
{

    @XmlAttribute(name = "service")
    protected String service;

    /**
     * Gets the value of the service property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getService()
    {
        if (service == null)
        {
            return "WFS";
        }
        else
        {
            return service;
        }
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setService(String value)
    {
        this.service = value;
    }

}
