//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.26 at 02:04:22 PM MST 
//

package net.opengis.wfs._110;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import net.opengis.ogc._110.GmlObjectIdType;

/**
 * 
 * A GetGmlObjectType element contains exactly one GmlObjectId. The value of the
 * gml:id attribute on that GmlObjectId is used as a unique key to retrieve the
 * complex element with a gml:id attribute with the same value.
 * 
 * 
 * <p>
 * Java class for GetGmlObjectType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="GetGmlObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/wfs}BaseRequestType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/ogc}GmlObjectId"/>
 *       &lt;/sequence>
 *       &lt;attribute name="outputFormat" type="{http://www.w3.org/2001/XMLSchema}string" default="GML3" />
 *       &lt;attribute name="traverseXlinkDepth" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="traverseXlinkExpiry" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetGmlObjectType", propOrder = { "gmlObjectId" })
public class GetGmlObjectType extends BaseRequestType
{

    @XmlElement(name = "GmlObjectId", namespace = "http://www.opengis.net/ogc", required = true)
    protected GmlObjectIdType gmlObjectId;

    @XmlAttribute(name = "outputFormat")
    protected String outputFormat;

    @XmlAttribute(name = "traverseXlinkDepth", required = true)
    protected String traverseXlinkDepth;

    @XmlAttribute(name = "traverseXlinkExpiry")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger traverseXlinkExpiry;

    /**
     * Gets the value of the gmlObjectId property.
     * 
     * @return possible object is {@link GmlObjectIdType }
     * 
     */
    public GmlObjectIdType getGmlObjectId()
    {
        return gmlObjectId;
    }

    /**
     * Sets the value of the gmlObjectId property.
     * 
     * @param value allowed object is {@link GmlObjectIdType }
     * 
     */
    public void setGmlObjectId(GmlObjectIdType value)
    {
        this.gmlObjectId = value;
    }

    /**
     * Gets the value of the outputFormat property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOutputFormat()
    {
        if (outputFormat == null)
        {
            return "GML3";
        }
        else
        {
            return outputFormat;
        }
    }

    /**
     * Sets the value of the outputFormat property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOutputFormat(String value)
    {
        this.outputFormat = value;
    }

    /**
     * Gets the value of the traverseXlinkDepth property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTraverseXlinkDepth()
    {
        return traverseXlinkDepth;
    }

    /**
     * Sets the value of the traverseXlinkDepth property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTraverseXlinkDepth(String value)
    {
        this.traverseXlinkDepth = value;
    }

    /**
     * Gets the value of the traverseXlinkExpiry property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getTraverseXlinkExpiry()
    {
        return traverseXlinkExpiry;
    }

    /**
     * Sets the value of the traverseXlinkExpiry property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setTraverseXlinkExpiry(BigInteger value)
    {
        this.traverseXlinkExpiry = value;
    }

}
