//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 10:22:41 AM MST 
//

package net.opengis.gml._212;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * A LinearRing is defined by four or more coordinate tuples, with linear
 * interpolation between them; the first and last coordinates must be
 * coincident.
 * 
 * 
 * <p>
 * Java class for LinearRingType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="LinearRingType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml}AbstractGeometryType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.opengis.net/gml}coord" maxOccurs="unbounded" minOccurs="4"/>
 *           &lt;element ref="{http://www.opengis.net/gml}coordinates"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinearRingType", propOrder = { "coord", "coordinates" })
public class LinearRingType extends AbstractGeometryType
{

    protected List<CoordType> coord;

    protected CoordinatesType coordinates;

    /**
     * Gets the value of the coord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the coord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCoord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CoordType
     * }
     * 
     * 
     */
    public List<CoordType> getCoord()
    {
        if (coord == null)
        {
            coord = new ArrayList<CoordType>();
        }
        return this.coord;
    }

    public boolean isSetCoord()
    {
        return ((this.coord != null) && (!this.coord.isEmpty()));
    }

    public void unsetCoord()
    {
        this.coord = null;
    }

    /**
     * Gets the value of the coordinates property.
     * 
     * @return possible object is {@link CoordinatesType }
     * 
     */
    public CoordinatesType getCoordinates()
    {
        return coordinates;
    }

    /**
     * Sets the value of the coordinates property.
     * 
     * @param value allowed object is {@link CoordinatesType }
     * 
     */
    public void setCoordinates(CoordinatesType value)
    {
        this.coordinates = value;
    }

    public boolean isSetCoordinates()
    {
        return (this.coordinates != null);
    }

}
