package io.opensphere.hud;

import java.util.Collection;
import java.util.Collections;

import io.opensphere.core.PluginLoaderData;
import io.opensphere.core.Toolbox;
import io.opensphere.core.api.Transformer;
import io.opensphere.core.api.adapter.PluginAdapter;
import io.opensphere.core.hud.util.FrameOptionsProvider;
import io.opensphere.hud.transformer.HUDTransformer;

/**
 * Main control class for the HUD plugin.
 */
public class HUDPlugin extends PluginAdapter
{
    /** The provider which handles the selection of options for HUD frames. */
    private FrameOptionsProvider myOptionsProvider;

    /**
     * The transformer that manages the publishing of geometries generated by
     * HUD components.
     */
    private HUDTransformer myTransformer;

    @Override
    public void close()
    {
        myTransformer.cleanup();
    }

    @Override
    public Collection<? extends Transformer> getTransformers()
    {
        return Collections.singleton(myTransformer);
    }

    @Override
    public void initialize(PluginLoaderData data, Toolbox toolbox)
    {
        myTransformer = new HUDTransformer(toolbox);

        myOptionsProvider = new FrameOptionsProvider(toolbox.getPreferencesRegistry());
        toolbox.getUIRegistry().getOptionsRegistry().addOptionsProvider(myOptionsProvider);
    }
}
