//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.30 at 12:22:16 PM MDT 
//


package net.opengis.kml._220;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class ASnippetElement
    extends JAXBElement<SnippetType>
{

    protected final static QName NAME = new QName("http://www.opengis.net/kml/2.2", "Snippet");

    public ASnippetElement(SnippetType value) {
        super(NAME, ((Class) SnippetType.class), null, value);
    }

    public ASnippetElement() {
        super(NAME, ((Class) SnippetType.class), null, null);
    }

}
