//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 10:22:41 AM MST 
//


package net.opengis.kml._220;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class ScaleScalar
    extends JAXBElement<Double>
{

    protected final static QName NAME = new QName("http://www.opengis.net/kml/2.2", "scale");

    public ScaleScalar(Double value) {
        super(NAME, (Double.class), null, value);
    }

    public ScaleScalar() {
        super(NAME, (Double.class), null, null);
    }

}
